/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CctvRouteImport } from './routes/cctv'
import { Route as DepartmentRouteImport } from './routes/department'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NonTeachingStaffRouteImport } from './routes/non-teaching-staff'
import { Route as StudentRouteImport } from './routes/student'
import { Route as TeachingStaffRouteImport } from './routes/teaching-staff'
import { Route as TicketsRouteImport } from './routes/tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CctvRoute = CctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentRoute = DepartmentRouteImport.update({
  id: '/department',
  path: '/department',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NonTeachingStaffRoute = NonTeachingStaffRouteImport.update({
  id: '/non-teaching-staff',
  path: '/non-teaching-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachingStaffRoute = TeachingStaffRouteImport.update({
  id: '/teaching-staff',
  path: '/teaching-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/cctv': typeof CctvRoute
  '/department': typeof DepartmentRoute
  '/faculty': typeof FacultyRoute
  '/login': typeof LoginRoute
  '/non-teaching-staff': typeof NonTeachingStaffRoute
  '/student': typeof StudentRoute
  '/teaching-staff': typeof TeachingStaffRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/cctv': typeof CctvRoute
  '/department': typeof DepartmentRoute
  '/faculty': typeof FacultyRoute
  '/login': typeof LoginRoute
  '/non-teaching-staff': typeof NonTeachingStaffRoute
  '/student': typeof StudentRoute
  '/teaching-staff': typeof TeachingStaffRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/audit': typeof AuditRoute
  '/cctv': typeof CctvRoute
  '/department': typeof DepartmentRoute
  '/faculty': typeof FacultyRoute
  '/login': typeof LoginRoute
  '/non-teaching-staff': typeof NonTeachingStaffRoute
  '/student': typeof StudentRoute
  '/teaching-staff': typeof TeachingStaffRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/audit'
    | '/cctv'
    | '/department'
    | '/faculty'
    | '/login'
    | '/non-teaching-staff'
    | '/student'
    | '/teaching-staff'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/audit'
    | '/cctv'
    | '/department'
    | '/faculty'
    | '/login'
    | '/non-teaching-staff'
    | '/student'
    | '/teaching-staff'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/audit'
    | '/cctv'
    | '/department'
    | '/faculty'
    | '/login'
    | '/non-teaching-staff'
    | '/student'
    | '/teaching-staff'
    | '/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AuditRoute: typeof AuditRoute
  CctvRoute: typeof CctvRoute
  DepartmentRoute: typeof DepartmentRoute
  FacultyRoute: typeof FacultyRoute
  LoginRoute: typeof LoginRoute
  NonTeachingStaffRoute: typeof NonTeachingStaffRoute
  StudentRoute: typeof StudentRoute
  TeachingStaffRoute: typeof TeachingStaffRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cctv': {
      id: '/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof CctvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/department': {
      id: '/department'
      path: '/department'
      fullPath: '/department'
      preLoaderRoute: typeof DepartmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-teaching-staff': {
      id: '/non-teaching-staff'
      path: '/non-teaching-staff'
      fullPath: '/non-teaching-staff'
      preLoaderRoute: typeof NonTeachingStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teaching-staff': {
      id: '/teaching-staff'
      path: '/teaching-staff'
      fullPath: '/teaching-staff'
      preLoaderRoute: typeof TeachingStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AuditRoute: AuditRoute,
  CctvRoute: CctvRoute,
  DepartmentRoute: DepartmentRoute,
  FacultyRoute: FacultyRoute,
  LoginRoute: LoginRoute,
  NonTeachingStaffRoute: NonTeachingStaffRoute,
  StudentRoute: StudentRoute,
  TeachingStaffRoute: TeachingStaffRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
